/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package smsims;

import smsims.member.EditMember;
import smsims.member.NewMember;

/**
 *
 * @author Lasith.Chandrasekara
 */
public class MemberPanel extends javax.swing.JPanel {

    /**
     * Creates new form MemberPanel
     */
    public MemberPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_member_tools = new javax.swing.JPanel();
        jb_newMember = new javax.swing.JButton();
        jb_editMember = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jp_memberMain = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(635, 510));
        setPreferredSize(new java.awt.Dimension(587, 433));

        jb_newMember.setText("New Member");
        jb_newMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_newMemberActionPerformed(evt);
            }
        });

        jb_editMember.setText("Edit/Delete Member");
        jb_editMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_editMemberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_member_toolsLayout = new javax.swing.GroupLayout(jp_member_tools);
        jp_member_tools.setLayout(jp_member_toolsLayout);
        jp_member_toolsLayout.setHorizontalGroup(
            jp_member_toolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_member_toolsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_member_toolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jp_member_toolsLayout.createSequentialGroup()
                        .addComponent(jb_newMember, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jb_editMember, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(423, Short.MAX_VALUE))))
        );
        jp_member_toolsLayout.setVerticalGroup(
            jp_member_toolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_member_toolsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jp_member_toolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb_editMember, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jp_member_toolsLayout.createSequentialGroup()
                        .addComponent(jb_newMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2)))
                .addGap(1, 1, 1)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setText("Member J panel");

        javax.swing.GroupLayout jp_memberMainLayout = new javax.swing.GroupLayout(jp_memberMain);
        jp_memberMain.setLayout(jp_memberMainLayout);
        jp_memberMainLayout.setHorizontalGroup(
            jp_memberMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_memberMainLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_memberMainLayout.setVerticalGroup(
            jp_memberMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_memberMainLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addContainerGap(417, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jp_memberMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jp_member_tools, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jp_member_tools, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jp_memberMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jb_newMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_newMemberActionPerformed
           NewMember newMember = new NewMember();
           newMember.setLocation(0, 00);
           newMember.setSize(1800, 1600);
           jp_memberMain.removeAll();
           jp_memberMain.add(newMember);
           jp_memberMain.revalidate();
           jp_memberMain.repaint();
    }//GEN-LAST:event_jb_newMemberActionPerformed

    private void jb_editMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_editMemberActionPerformed
           EditMember editMember = new EditMember();
           editMember.setLocation(0, 00);
           editMember.setSize(1800, 1600);
           jp_memberMain.removeAll();
           jp_memberMain.add(editMember);
           jp_memberMain.revalidate();
           jp_memberMain.repaint();        // TODO add your handling code here:
    }//GEN-LAST:event_jb_editMemberActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jb_editMember;
    private javax.swing.JButton jb_newMember;
    private javax.swing.JPanel jp_memberMain;
    private javax.swing.JPanel jp_member_tools;
    // End of variables declaration//GEN-END:variables
}
