/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package smsims.member;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import smsims.db.DbOperation;
import smsims.om.Member;

/**
 *
 * @author Lasith
 */
public class NewMember extends javax.swing.JPanel {

    /**
     * Creates new form NewMember
     */
    public NewMember() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtf_mname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtf_tpNumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtf_department = new javax.swing.JTextField();
        jb_saveMember = new javax.swing.JButton();
        jb_clearMember = new javax.swing.JButton();

        jLabel1.setText("Name");

        jLabel2.setLabelFor(jtf_mname);
        jLabel2.setText("Tp number");

        jLabel3.setText("Department");

        jb_saveMember.setText("Save");
        jb_saveMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_saveMemberActionPerformed(evt);
            }
        });

        jb_clearMember.setText("Clear");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_mname, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jtf_department, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                .addComponent(jtf_tpNumber, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jb_saveMember)
                        .addGap(42, 42, 42)
                        .addComponent(jb_clearMember)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtf_mname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtf_tpNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_saveMember)
                    .addComponent(jb_clearMember))
                .addContainerGap(48, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jb_saveMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_saveMemberActionPerformed
        if(!validateFields()) {
            return;
        }
        DbOperation dbOperation = new DbOperation();
        
        Member member = new Member();
        member.setName(jtf_mname.getText());
        member.setTpNumber(jtf_tpNumber.getText());
        member.setDepartment(jtf_department.getText());
        try {
            dbOperation.insertMember(member);
            javax.swing.JOptionPane.showMessageDialog(this, "Member " + jtf_mname.getText() + "  is saved.", "Alert", 1);
        } catch (Exception ex) {
            Logger.getLogger(NewMember.class.getName()).log(Level.SEVERE, null, ex);
            javax.swing.JOptionPane.showMessageDialog(this, "Member " + jtf_mname.getText() + "  is not saved.", "Alert", 1);
        }
    }//GEN-LAST:event_jb_saveMemberActionPerformed

    private boolean validateFields() {
        boolean isSuccess = true;
        if (jtf_mname.getText() == null || jtf_mname.getText().equals("")) {            
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter name", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (!validateTpNumber(jtf_tpNumber.getText())) {
            return false;
        }
        if (jtf_department.getText() == null || jtf_department.getText().equals("")) {            
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter department", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return isSuccess;
    }
    
    public boolean validateTpNumber(String tpNumber) {
        boolean isSuccess = true;
        try{
            Integer.parseInt(tpNumber);
        } catch (NumberFormatException e) {
            isSuccess = false;
        }
        if (tpNumber.length() != 10){
            isSuccess = false;
        }
        if (!isSuccess) {            
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter valid phone number", "Error", JOptionPane.ERROR_MESSAGE);
        }
        return isSuccess;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jb_clearMember;
    private javax.swing.JButton jb_saveMember;
    private javax.swing.JTextField jtf_department;
    private javax.swing.JTextField jtf_mname;
    private javax.swing.JTextField jtf_tpNumber;
    // End of variables declaration//GEN-END:variables
}
