/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package smsims.member;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import smsims.db.DbOperation;
import smsims.member.util.ValidationUtil;
import smsims.om.Member;
import smsims.om.MemberStatus;

/**
 *
 * @author Lasith
 */
public class NewMember extends javax.swing.JPanel {

    /**
     * Creates new form NewMember
     */
    public NewMember() {
        initComponents();
        loadValues();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtf_mname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtf_tpNumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jb_saveMember = new javax.swing.JButton();
        jb_clearMember = new javax.swing.JButton();
        jc_department = new javax.swing.JComboBox();
        jc_site = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jc_mgtLevel = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtf_empCode = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jcb_member_status = new javax.swing.JComboBox();

        jLabel1.setText("Name");

        jLabel2.setLabelFor(jtf_mname);
        jLabel2.setText("Tp number");

        jLabel3.setText("Department");

        jb_saveMember.setText("Save");
        jb_saveMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_saveMemberActionPerformed(evt);
            }
        });

        jb_clearMember.setText("Clear");

        jc_department.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Geo-Cycle", "HR" }));

        jc_site.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CMB", "Galle" }));

        jLabel4.setText("Site");

        jc_mgtLevel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FML", "SML", "TML" }));

        jLabel5.setText("Mgt level");

        jLabel6.setText("Emp code");

        jLabel7.setText("Status");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_mname, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jc_mgtLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtf_empCode, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jc_department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(45, 45, 45)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel7)))
                                    .addComponent(jc_site, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtf_tpNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcb_member_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jb_saveMember)
                        .addGap(42, 42, 42)
                        .addComponent(jb_clearMember)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtf_mname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_tpNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jLabel6)
                                .addComponent(jtf_empCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jc_department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addComponent(jLabel1))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jc_site, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jcb_member_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jc_mgtLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_saveMember)
                    .addComponent(jb_clearMember))
                .addContainerGap(65, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jb_saveMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_saveMemberActionPerformed
        Member member = new Member();
        String memberDepatrment = jc_department.getSelectedItem().toString();
        String memberSite = jc_site.getSelectedItem().toString();
        String memberMgtLevel = jc_mgtLevel.getSelectedItem().toString();
        
        member.setName(jtf_mname.getText());
        member.setTpNumber(jtf_tpNumber.getText());
        member.setDepartment(memberDepatrment);
        member.setSite(memberSite);
        member.setMgtLevel(memberMgtLevel);
        member.setEmpCode(jtf_empCode.getText());
        member.setStatus(jcb_member_status.getSelectedItem().toString());
        
        try {
            if(!ValidationUtil.validateFields(member, this, false)) {
                return;
            }
        } catch (Exception ex) {
            Logger.getLogger(NewMember.class.getName()).log(Level.SEVERE, null, ex);
            javax.swing.JOptionPane.showMessageDialog(this, "Member not saved." + ex.getMessage(), "Error", 1);
        }
        DbOperation dbOperation = new DbOperation();       

        try {
            dbOperation.insertMember(member);
            javax.swing.JOptionPane.showMessageDialog(this, "Member " + jtf_mname.getText() + "  is saved.", "Alert", 1);
        } catch (Exception ex) {
            Logger.getLogger(NewMember.class.getName()).log(Level.SEVERE, null, ex);
            javax.swing.JOptionPane.showMessageDialog(this, "Member " + jtf_mname.getText() + "  is not saved." 
                    + ex.getMessage(), "Error", 1);
        }
    }//GEN-LAST:event_jb_saveMemberActionPerformed
    
    private void loadValues() {
        for (MemberStatus status : MemberStatus.values()) {            
            jcb_member_status.addItem(status);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jb_clearMember;
    private javax.swing.JButton jb_saveMember;
    private javax.swing.JComboBox jc_department;
    private javax.swing.JComboBox jc_mgtLevel;
    private javax.swing.JComboBox jc_site;
    private javax.swing.JComboBox jcb_member_status;
    private javax.swing.JTextField jtf_empCode;
    private javax.swing.JTextField jtf_mname;
    private javax.swing.JTextField jtf_tpNumber;
    // End of variables declaration//GEN-END:variables
}
